"""optimize_account_scoped_indexes

Revision ID: 02c422e56e2c
Revises: 207f3eda11c5
Create Date: 2026-04-02 10:58:44.504408

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '02c422e56e2c'
down_revision: Union[str, Sequence[str], None] = '207f3eda11c5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_accounts_id'), table_name='accounts')
    op.drop_index(op.f('ix_customers_account_id'), table_name='customers')
    op.drop_index(op.f('ix_customers_id'), table_name='customers')
    op.drop_index(op.f('ix_customers_name'), table_name='customers')
    op.create_index('ix_customers_account_id_name', 'customers', ['account_id', 'name'], unique=False)
    op.drop_index(op.f('ix_employees_account_id'), table_name='employees')
    op.drop_index(op.f('ix_employees_id'), table_name='employees')
    op.create_index('ix_employees_account_id_first_name_last_name', 'employees', ['account_id', 'first_name', 'last_name'], unique=False)
    op.drop_index(op.f('ix_invite_codes_id'), table_name='invite_codes')
    op.drop_index(op.f('ix_schedule_entries_account_id'), table_name='schedule_entries')
    op.drop_index(op.f('ix_schedule_entries_customer_id'), table_name='schedule_entries')
    op.drop_index(op.f('ix_schedule_entries_date'), table_name='schedule_entries')
    op.drop_index(op.f('ix_schedule_entries_employee_id'), table_name='schedule_entries')
    op.drop_index(op.f('ix_schedule_entries_id'), table_name='schedule_entries')
    op.create_index('ix_schedule_entries_account_id_customer_id', 'schedule_entries', ['account_id', 'customer_id'], unique=False)
    op.create_index('ix_schedule_entries_account_id_date_start_time_id', 'schedule_entries', ['account_id', 'date', 'start_time', 'id'], unique=False)
    op.create_index('ix_schedule_entries_account_id_employee_id', 'schedule_entries', ['account_id', 'employee_id'], unique=False)
    op.drop_index(op.f('ix_user_account_memberships_id'), table_name='user_account_memberships')
    op.drop_index(op.f('ix_user_account_memberships_user_id'), table_name='user_account_memberships')
    op.create_index('ix_user_account_memberships_user_id_is_active_created_at_id', 'user_account_memberships', ['user_id', 'is_active', 'created_at', 'id'], unique=False)
    op.drop_index(op.f('ix_users_id'), table_name='users')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.drop_index('ix_user_account_memberships_user_id_is_active_created_at_id', table_name='user_account_memberships')
    op.create_index(op.f('ix_user_account_memberships_user_id'), 'user_account_memberships', ['user_id'], unique=False)
    op.create_index(op.f('ix_user_account_memberships_id'), 'user_account_memberships', ['id'], unique=False)
    op.drop_index('ix_schedule_entries_account_id_employee_id', table_name='schedule_entries')
    op.drop_index('ix_schedule_entries_account_id_date_start_time_id', table_name='schedule_entries')
    op.drop_index('ix_schedule_entries_account_id_customer_id', table_name='schedule_entries')
    op.create_index(op.f('ix_schedule_entries_id'), 'schedule_entries', ['id'], unique=False)
    op.create_index(op.f('ix_schedule_entries_employee_id'), 'schedule_entries', ['employee_id'], unique=False)
    op.create_index(op.f('ix_schedule_entries_date'), 'schedule_entries', ['date'], unique=False)
    op.create_index(op.f('ix_schedule_entries_customer_id'), 'schedule_entries', ['customer_id'], unique=False)
    op.create_index(op.f('ix_schedule_entries_account_id'), 'schedule_entries', ['account_id'], unique=False)
    op.create_index(op.f('ix_invite_codes_id'), 'invite_codes', ['id'], unique=False)
    op.drop_index('ix_employees_account_id_first_name_last_name', table_name='employees')
    op.create_index(op.f('ix_employees_id'), 'employees', ['id'], unique=False)
    op.create_index(op.f('ix_employees_account_id'), 'employees', ['account_id'], unique=False)
    op.drop_index('ix_customers_account_id_name', table_name='customers')
    op.create_index(op.f('ix_customers_name'), 'customers', ['name'], unique=False)
    op.create_index(op.f('ix_customers_id'), 'customers', ['id'], unique=False)
    op.create_index(op.f('ix_customers_account_id'), 'customers', ['account_id'], unique=False)
    op.create_index(op.f('ix_accounts_id'), 'accounts', ['id'], unique=False)
    # ### end Alembic commands ###
